[install]
# Install mode: online or offline
mode = "development"

# cache directory
cache_dir = "node_modules/.cache"

# enable peer dependencies
allow-optional-dependencies = true

[compile]
# Target for compilation
target = "bun"

# Do not use esbuild's loose mode
looseEquality = false

[test]
# Test configuration
snapshots = "./test/snapshots"
timeout_ms = 5000

[debug]
# Show logs
logs_visible = false
